// İstasyon kimlikleri — her istasyona bir cümlelik ruh.
// Katalog metnidir; iddia değil atmosfer taşır. Burada olmayan istasyonda satır görünmez.

const TANIMLAR: Record<string, { tr: string; en?: string }> = {
  "arabesk-fm": { tr: "Gece yarısı damar; direksiyon başı arabesk.", en: "Midnight arabesk for the long drive home." },
  "virgin-radio": { tr: "İstanbul'un cilalı pop vitrini.", en: "Istanbul's polished pop storefront." },
  "damar-turk-fm": { tr: "Adı üstünde: damardan, sulandırmadan.", en: "Heartbreak straight from the vein." },
  "kafa-radyo": { tr: "Sabah trafiğinin muhabbetçisi.", en: "Morning-traffic talk and hits." },
  "radyo-7": { tr: "Türkçe popun emektar frekansı.", en: "A veteran of Turkish pop airwaves." },
  "turkulerle-turkiye": { tr: "Memleket hasretine türkü sarar.", en: "Folk songs for homesickness." },
  "radyo-siran": { tr: "Gümüşhane'den yayla havası.", en: "Highland air from Gümüşhane." },
  "metro-fm": { tr: "Şehrin ritmine yabancı hit'ler.", en: "Foreign hits on the city's pulse." },
  "ankara-havalari": { tr: "Başkentin oyun havası; misket ve zeybek.", en: "Ankara's folk-dance frequency." },
  "altin-sarkilar": { tr: "Sararmış fotoğraflardan yükselen şarkılar.", en: "Songs rising from yellowed photographs." },
  "dinamo-sleep": { tr: "Uyumadan önce son frekans.", en: "The last frequency before sleep." },
  "super-fm": { tr: "Doksanlardan beri pop'un ana damarı.", en: "Mainline Turkish pop since the '90s." },
  "90lar": { tr: "Kasetin A yüzü: doksanlar burada bitmedi.", en: "Side A forever: the '90s never ended here." },
  "pal-station": { tr: "Kulüp gecesinin radyodaki hali.", en: "Club night, radio edition." },
  "pal-nostalji": { tr: "Eski aşklar için ışıklar kısık.", en: "Lights dimmed for old flames." },
  "pal-doga": { tr: "Türkü ile dağ havası bir arada.", en: "Folk songs with mountain air." },
  "pop-90": { tr: "Doksanlar pop'u, bitmeyen okul çıkışı.", en: "'90s pop, an endless school run." },
  "dinamo-deep": { tr: "Derin ev; gece yürüyüşlerinin sesi.", en: "Deep house for night walks." },
  "joy-fm": { tr: "Yumuşak pop, sakin ofis saatleri.", en: "Soft pop for calm office hours." },
  "alem-fm": { tr: "Eğlencenin yüksek sesli hali.", en: "The loud end of Turkish pop." },
  "dost-radyo": { tr: "Türkünün dost meclisi.", en: "A friendly gathering of folk songs." },
  "dinamo-caffe": { tr: "Kahve buharına karışan elektronik.", en: "Electronica dissolving into coffee steam." },
  "dinamo-discotheque": { tr: "Aynalı top hâlâ dönüyor.", en: "The mirror ball still spins." },
  "itu-klasik": { tr: "Kampüsten yükselen oda müziği.", en: "Chamber music from campus." },
  "radio-zetzet": { tr: "Cazın geç saat sohbeti.", en: "Jazz's late-night conversation." },
  "turku-radyo": { tr: "Anadolu'nun sözlü hafızası.", en: "Anatolia's sung memory." },
  "sizir-fm": { tr: "Sivas kökünden türkü sızıntısı.", en: "Folk seeping from Sivas roots." },
  "beste-fm": { tr: "Türkçe popun orta şekeri.", en: "Turkish pop, medium sweet." },
  "hey-radyo": { tr: "İzmir'den güler yüzlü pop.", en: "Cheerful pop out of İzmir." },
  "radyo-kent": { tr: "Şehir içi kullanım için pop.", en: "Pop for city use." },
  "ask-fm": { tr: "Adı gibi: bütün şarkılar aşka çıkar.", en: "Every song here leads to love." },
  "joyturk-rock": { tr: "Türkçe rock'ın radyo sahnesi.", en: "The radio stage of Turkish rock." },
  "radyo-odtu-rock": { tr: "Kampüs rock'ı, amfi çıkışı.", en: "Campus rock, straight from the lecture hall." },
  "turk-rock-fm": { tr: "Sazlı gitarlı isyan arşivi.", en: "An archive of Anatolian rebellion." },
  "radyo-a": { tr: "Eskişehir'in kampüs alternatifi.", en: "Eskişehir's campus alternative." },
  "enradio": { tr: "Bağımsız kulaklar için alternatif akış.", en: "An alternative stream for independent ears." },
  "loops-radio": { tr: "Sonsuz döngüde elektronik.", en: "Electronica on infinite loop." },
  "mayday-records": { tr: "Plak çantasından taze elektronik.", en: "Fresh electronica from the record bag." },
  "dinamo-smog": { tr: "Şehir dumanına ayarlı bas.", en: "Bass tuned to city smog." },
  "romantik-ses-isparta": { tr: "Isparta'dan gül kokulu nostalji.", en: "Rose-scented nostalgia from Isparta." },
  "slow-fm": { tr: "Yavaş şarkılar, uzun bakışlar.", en: "Slow songs, long glances." },
  "radyo-arabesk": { tr: "Arabeskin ansiklopedik rafı.", en: "The encyclopedic shelf of arabesk." },
  "radyo-45lik": { tr: "45'lik plakların iğne cızırtısı.", en: "The needle crackle of 45s." },
  "joyturk": { tr: "Türkçe pop'un güncel nabzı.", en: "The current pulse of Turkish pop." },
  "borusan-klasik": { tr: "Konser salonu, cebinde.", en: "A concert hall in your pocket." },
  "park-fm": { tr: "Parkta akşamüstü arabesk.", en: "Arabesk at dusk in the park." },
  "baba-radyo": { tr: "Arabeskin babadan kalma frekansı.", en: "Arabesk, inherited from the elders." },
  "halk-radyo": { tr: "Halkın istek hattı.", en: "The people's request line." },
  "radyo-duet": { tr: "Türkçe pop, çift sesli.", en: "Turkish pop in duet." },
  "can-radyo": { tr: "Candan türküler, cana yakın.", en: "Folk songs, warm and close." },
  "radyo-ekin": { tr: "Türkünün ekin tarlası.", en: "A harvest field of folk song." },
  "radio-antalya": { tr: "Akdeniz akşamına alternatif.", en: "An alternative for Mediterranean evenings." },
  "radyo-gokceada": { tr: "Ada rüzgârıyla gelen pop.", en: "Pop carried on island wind." },
  "slow-turk": { tr: "Türkçe slow'un başkenti.", en: "The capital of Turkish slow." },
  "trt-fm": { tr: "Devlet radyosunun pop kanadı.", en: "The pop wing of public radio." },
  "kral-turk-fm": { tr: "Kral ailesinin Türkçe kanadı.", en: "The Turkish wing of the Kral family." },
  "radyo-seymen": { tr: "Ankara'nın efeleri iş başında.", en: "Ankara's folk bravado on air." },
  "radyo-voyage": { tr: "Sözsüz yolculuk müziği.", en: "Wordless travel music." },
  "gozyasi-fm": { tr: "Adı yeterince açık: mendil hazırla.", en: "The name says it: bring tissues." },
  "kalp-fm": { tr: "Nostaljinin kalp atışı.", en: "Nostalgia's heartbeat." },
  "fakir-fm": { tr: "Arabeskin gururlu yoksulluğu.", en: "The proud poverty of arabesk." },
  "erzincan-cem-radyo": { tr: "Erzincan'dan deyişler ve nefesler.", en: "Alevi hymns and verses from Erzincan." },
  "radyo-odtu": { tr: "ODTÜ'den bağımsız kulak zevki.", en: "Independent taste from METU." },
  "dinamo-fm-locodyno": { tr: "Rayından çıkmış elektronik.", en: "Electronica off the rails." },
  "keyf-station": { tr: "Keyfe keder pop seçkisi.", en: "Pop at leisure." },
  "radyo-eksen": { tr: "Alternatifin İstanbul'daki ekseni.", en: "Istanbul's axis of alternative." },
  "apacik-radyo": { tr: "Açık Radyo: dinleyicisinin omuzlarında.", en: "Listener-funded, fiercely open." },
  "kiyi-caz": { tr: "Kıyıda caz; dalgalar ritim tutar.", en: "Jazz at the shoreline, waves on rhythm." },
  "radyoaura": { tr: "Cazın loş ışıklı salonu.", en: "Jazz in a dim-lit lounge." },
  "radio-mydonose": { tr: "Pistin ışıl ışıl elektroniği.", en: "The dance floor's glittering electronica." },
  "max-fm": { tr: "Rock'ın yüksek voltajlı hattı.", en: "Rock's high-voltage line." },
  "kiss-turk": { tr: "Türkçe pop'a öpücük kondurur.", en: "A kiss blown at Turkish pop." },
  "tgrt-fm": { tr: "Türkçe pop'un aile boyu sofrası.", en: "A family table of Turkish pop." },
  "turkiyem-fm": { tr: "Memleket şarkılarının buluşması.", en: "Where hometown songs meet." },
  "radyo-karadeniz": { tr: "Kemençe rüzgârı, hamsi tadı.", en: "Black Sea wind, kemençe strings." },
  "radyo-alaturka": { tr: "Türk sanat müziğinin fasıl gecesi.", en: "A classical Turkish music soirée." },
  "hayatmix-arabesk": { tr: "Arabeskin karışık kaseti.", en: "The arabesk mixtape." },
  "radyo-turku": { tr: "Türkü burada ev sahibi.", en: "Folk song is the host here." },
  "dt-nostalji": { tr: "Tozlu raflardan seçme nostalji.", en: "Nostalgia picked from dusty shelves." },
  "dijital-slow": { tr: "Yavaşlığın dijital hali.", en: "Slowness, digitized." },
  "retro-turk": { tr: "Retronun Türkçe sözlüsü.", en: "Retro with Turkish lyrics." },
  "radyo-taksi": { tr: "Gece taksisinin radyosu.", en: "The night cab's radio." },
  "ktu": { tr: "Trabzon kampüsünden nostalji.", en: "Nostalgia from the Trabzon campus." },
  "dinamo-fm-legacy": { tr: "dinamo'nun miras arşivi.", en: "dinamo's legacy archive." },
  "dinamo-fm-fluent": { tr: "Akışkan elektronik; kesintisiz.", en: "Fluent, seamless electronica." },
  "loops-radio-progressive": { tr: "Progresif döngünün derin ucu.", en: "The deep end of the progressive loop." },

  // — DÜNYA —
  "somafm-groove-salad": { tr: "San Francisco'dan ağır çekim ambient salatası.", en: "A slow-motion ambient salad from San Francisco." },
  "somafm-indie-pop": { tr: "Bağımsız pop'un güneşli kaldırımı.", en: "The sunny sidewalk of indie pop." },
  "radio-paradise": { tr: "Dinleyici destekli cennet; reklamsız, ince elenmiş.", en: "Listener-funded paradise, hand-mixed and ad-free." },
  "radio-paradise-rock": { tr: "Cennetin gitarlı yamacı.", en: "Paradise, the guitar slope." },
  "tsf-jazz": { tr: "Paris'te gece yarısı caz kulübü.", en: "A midnight jazz club in Paris." },
  "radio-swiss-classic": { tr: "İsviçre saati gibi işleyen klasik.", en: "Classical music, precise as a Swiss watch." },
  "somafm-secret-agent": { tr: "Ajan filmi müziği; martini soğuk.", en: "Spy-film lounge; the martini stays cold." },
  "somafm-metal": { tr: "Metal dedektörü: ağır ve keskin ne varsa.", en: "A metal detector for all things heavy." },
  "kexp": { tr: "Seattle'ın efsane bağımsız frekansı.", en: "Seattle's legendary independent frequency." },
  "nts-1": { tr: "Londra yeraltısının açık kanalı.", en: "An open channel to London's underground." },
  "los40": { tr: "İspanya'nın kırk yıllık hit listesi.", en: "Spain's chart machine since the '60s." },
  "radio-number-one": { tr: "Milano'dan bir numaralık pop iddiası.", en: "Milan pop with a number-one attitude." },
  "virgin-radio-italia": { tr: "İtalyan işi rock vitrini.", en: "Rock, Italian-tailored." },
  "diana-krall": { tr: "Yalnızca Diana Krall; başka soru yok.", en: "Diana Krall only; no further questions." },
  "italo-power": { tr: "İtalo disko: brantatörlü zaman makinesi.", en: "Italo disco, a synth-driven time machine." },
  "france-musique": { tr: "Fransız devlet radyosunun konser salonu.", en: "The concert hall of Radio France." },
  "venice-classic-radio": { tr: "Venedik kanallarında yankılanan klasik.", en: "Classical echoing down Venetian canals." },
  "klara-nostalgia": { tr: "Brüksel'den kadife nostalji.", en: "Velvet nostalgia out of Brussels." },
  "wqxr": { tr: "New York'un klasik müzik kulesi.", en: "New York's classical tower." },
  "classical-kusc": { tr: "Los Angeles güneşinde klasik.", en: "Classical under the Los Angeles sun." },
  "radio-classique": { tr: "Paris usulü klasik zarafet.", en: "Classical elegance, Paris style." },
  "concertzender-klassiek": { tr: "Hollanda'nın titiz konser yayıncısı.", en: "The Netherlands' meticulous concert broadcaster." },
  "jazz24": { tr: "Günde yirmi dört saat caz mesaisi.", en: "Jazz on a twenty-four-hour shift." },
  "wbgo": { tr: "Newark'tan cazın ana yurdu.", en: "Jazz's home ground in Newark." },
  "radio-swiss-jazz": { tr: "Temiz çalınmış İsviçre cazı.", en: "Swiss jazz, cleanly poured." },
  "wfmu": { tr: "Serbest biçimli radyonun deney tüpü.", en: "The test tube of freeform radio." },
  "wxpn": { tr: "Philadelphia'nın şarkı yazarı dostu.", en: "Philadelphia's friend of the songwriter." },
  "fluxfm": { tr: "Berlin'in akıntıya karşı frekansı.", en: "Berlin's against-the-current frequency." },
  "rinse-fm": { tr: "Londra bas kültürünün korsan ruhu.", en: "The pirate spirit of London bass." },
  "worldwide-fm": { tr: "Dünya müziğinin Londra santrali.", en: "London's switchboard for global sounds." },
  "somafm-drone-zone": { tr: "Yerçekimsiz uğultu bölgesi.", en: "A gravity-free drone zone." },
  "somafm-space-station": { tr: "Yörüngedeki istasyondan sinyal.", en: "Signals from the orbiting station." },
  "fip": { tr: "Paris'in kestirilemez müzik sekreteri.", en: "Paris's unpredictable music curator." },
  "nrj-belgie": { tr: "Brüksel'de yüksek enerji pop.", en: "High-energy pop in Brussels." },
  "absolute-radio-80s": { tr: "Seksenlerin mutlak arşivi.", en: "The absolute archive of the '80s." },
  "capital-fm-uk": { tr: "Britanya pop'unun başkent hattı.", en: "The capital line of British pop." },
  "radio-paradise-mellow": { tr: "Cennetin alçak sesli köşesi.", en: "Paradise, the quiet corner." },
  "somafm-deep-space-one": { tr: "Derin uzaya tek yön bilet.", en: "A one-way ticket to deep space." },
  "somafm-lush": { tr: "Yemyeşil, rüya gibi pop.", en: "Lush, dream-laced pop." },
  "best-of-rock-fm-alternative-rock": { tr: "Alman işi alternatif rock rafı.", en: "A German shelf of alternative rock." },
  "technolovers-deep-house": { tr: "Derin ev müziğinin makine dairesi.", en: "The engine room of deep house." },
  "eurodance-90-radio": { tr: "Doksanların eurodance pisti.", en: "The '90s eurodance floor." },
  "oui-fm": { tr: "Fransız rock'ının 'evet'çisi.", en: "French rock's resounding oui." },
  "bfm-radio-128-mp3": { tr: "Fransız pop'un gündelik akışı.", en: "The everyday stream of French pop." },
  "urban-hit-maroc": { tr: "Paris-Kazablanka arası urban hat.", en: "An urban line between Paris and Casablanca." },
  "heart-80s": { tr: "Kalbi seksenlerde atan İngiliz pop'u.", en: "British pop with an '80s heartbeat." },
  "tmm-1": { tr: "Camden'dan elektronik birinci kanal.", en: "Camden electronics, channel one." },
  "heart-70s": { tr: "Yetmişlerin kalp ritmi.", en: "The heart rate of the '70s." },
  "gold": { tr: "Altın çağ şarkılarının kasası.", en: "The vault of golden-age songs." },
  "smooth-chill": { tr: "Pürüzsüz, serin, akşamüstü.", en: "Smooth, cool, late afternoon." },
  "heart-dance": { tr: "Kalp atışı pist temposunda.", en: "A heartbeat at dance-floor tempo." },
  "heart-90s": { tr: "Doksanlara ayarlı kalp.", en: "A heart tuned to the '90s." },
  "tmm-2": { tr: "Camden'dan elektronik ikinci kanal.", en: "Camden electronics, channel two." },
  "love-radio-only-love-songs-70s80s90s": { tr: "Üç on yıllık aşk şarkısı stoğu.", en: "Three decades of love songs in stock." },
  "chillout-ibiza-fm": { tr: "İbiza gün batımının uzaktan kumandası.", en: "A remote control for Ibiza sunsets." },
  "exclusively-dire-straits": { tr: "Yalnızca Dire Straits; gitar konuşur.", en: "Dire Straits only; the guitar does the talking." },
  "capital-dance": { tr: "Britanya'nın dans vardiyası.", en: "Britain's dance shift." },
  "classic-vinyl-hd": { tr: "Plak cızırtısı yüksek çözünürlükte.", en: "Vinyl crackle in high definition." },
  "walm-old-time-radio": { tr: "Radyonun siyah-beyaz çağından yayın.", en: "Broadcasting from radio's black-and-white era." },
  "181-fm-the-beat-hiphop-r-b": { tr: "Virginia'dan kesintisiz beat.", en: "Uninterrupted beats out of Virginia." },
  "funky-radio-only-funk-music-60-s-70-s": { tr: "Funk'ın altmışlar-yetmişler ambarı.", en: "A warehouse of '60s–'70s funk." },
  "miami-beach-radio": { tr: "Miami sahilinde açık hava pop'u.", en: "Open-air pop on Miami sand." },
  "z-92-miami-92-3-fm-wcmq-fm-spanish-broad": { tr: "Miami'nin İspanyolca ritim kanalı.", en: "Miami's Spanish-language rhythm channel." },
  "classic-hits-radio-70-80-discofunk-moder": { tr: "Disko-funk'tan modern soul'a köprü.", en: "A bridge from disco-funk to modern soul." },
  "radio-armisa": { tr: "İtalya'dan elektronik el işçiliği.", en: "Electronic craftsmanship from Italy." },
  "70-80-hits-hq": { tr: "Milano'dan yüksek kalite retro hit.", en: "High-fidelity retro hits from Milan." },
  "classic-hits-radio-italia": { tr: "İtalyan klasik hit deposu.", en: "Italy's classic-hit depot." },
  "italia-italia-70": { tr: "Yetmişlerin İtalya'sına açılan pencere.", en: "A window onto 1970s Italy." },
  "new-hits-radio-italia": { tr: "İtalyan pop'unun taze rafı.", en: "The fresh shelf of Italian pop." },
  "rai-2": { tr: "İtalyan devlet radyosunun pop kanalı.", en: "The pop channel of Italian public radio." },
  "cafe-del-mar": { tr: "İbiza'da gün batımı ayini.", en: "The sunset ritual of Ibiza." },
  "remember-the-music-fm-96-6": { tr: "Valensiya'dan hatırlanası elektronik.", en: "Memorable electronics from Valencia." },
  "punk-irratia": { tr: "Bask ülkesinden punk bildirisi.", en: "A punk manifesto from Basque country." },
  "radio-planeta-costa-del-sol": { tr: "Güneş kıyısının elektronik gezegeni.", en: "The electronic planet of the sunny coast." },
  "costa-del-mar-smooth-jazz": { tr: "Deniz kenarında yumuşak caz.", en: "Smooth jazz at the water's edge." },
  "intense-radio-we-love-dance-256k": { tr: "Yoğunluğu yüksek dans akışı.", en: "Dance at maximum intensity." },
  "arrow-classic-rock": { tr: "Hollanda'nın klasik rock oku.", en: "The Dutch arrow of classic rock." },
  "npo-radio-5": { tr: "Hollanda kamusal radyosunun nostaljik kanadı.", en: "The nostalgic wing of Dutch public radio." },
  "qmusic": { tr: "Hollanda pop'unun parlak yüzü.", en: "The bright face of Dutch pop." },
  "fantasy-italo-dance-90s-radio": { tr: "İtalo-dance fantezisi, doksanlar modeli.", en: "An italo-dance fantasy, '90s model." },
  "grolloo-radio": { tr: "Hollanda köyünden blues kokusu.", en: "Blues drifting from a Dutch village." },
  "jazz-de-ville-chill": { tr: "Şehir cazının serin terası.", en: "The cool terrace of city jazz." },
  "sjeffm": { tr: "Weert'ten mahalle nostaljisi.", en: "Neighborhood nostalgia from Weert." },
  "rtbf-classic-21": { tr: "Valonya'nın klasik rock kanalı.", en: "Wallonia's classic rock channel." },
  "pure-fm": { tr: "Belçika'nın saf pop damarı.", en: "Belgium's pure pop vein." },
  "mynoise-pure-nature": { tr: "Müzik değil: yağmur, rüzgâr, orman.", en: "Not music: rain, wind, forest." },
  "top-radio-retro": { tr: "Belçika retrosunun üst rafı.", en: "The top shelf of Belgian retro." },
  "rtbf-vivacite-bruxelles": { tr: "Brüksel'in canlı gündelik sesi.", en: "The lively daily voice of Brussels." },
  "tipik": { tr: "Belçika gençliğinin tipik olmayan kanalı.", en: "Belgium's untypical youth channel." },
  "80s-forever-we-keep-the-80s-alive": { tr: "Seksenleri yaşatma derneği, Zürih şubesi.", en: "The keep-the-'80s-alive society, Zurich chapter." },
  "vintage-radio": { tr: "İsviçre işi vintage seçki.", en: "A vintage selection, Swiss-made." },
  "fm4-orf": { tr: "Viyana'nın alternatif gece nöbeti.", en: "Vienna's alternative night watch." },
  "lounge-fm-100-austria": { tr: "Avusturya'dan yüzde yüz salon müziği.", en: "One hundred percent Austrian lounge." },
  "orf-hitradio-o3-hq": { tr: "Avusturya'nın ana hit şebekesi.", en: "Austria's main hit grid." },
  "radio-u1-tirol": { tr: "Tirol dağlarından pop yankısı.", en: "Pop echoing off the Tyrolean Alps." },
  "arabella-relax": { tr: "Viyana'da gevşeme frekansı.", en: "Vienna's relaxation frequency." },
  "radio-vorarlberg": { tr: "Avusturya'nın batı ucundan yayın.", en: "Broadcasting from Austria's western edge." },
  "rfm": { tr: "Portekiz pop'unun ana caddesi.", en: "The main street of Portuguese pop." },
  "radio-comercial-portugal": { tr: "Lizbon sabahlarının neşeli sesi.", en: "The cheerful sound of Lisbon mornings." },
  "m80-radio-80s": { tr: "Portekiz'den seksenler ekspresi.", en: "The '80s express out of Portugal." },
  "jovembsk": { tr: "Portekiz gençliğinin dalga boyu.", en: "The wavelength of Portuguese youth." },
  "radio-amor-portugal": { tr: "Portekizce aşk şarkıları hattı.", en: "A hotline of Portuguese love songs." },
  "smooth-fm-aac": { tr: "Lizbon'da ipeksi caz saatleri.", en: "Silky jazz hours in Lisbon." },
  "zeppelin-106-7": { tr: "Atina semalarında rock zeplini.", en: "A rock zeppelin over Athens." },
  "vanilla-radio-smooth-flavors": { tr: "Vanilya tadında yumuşak seçki.", en: "A smooth selection, vanilla-flavored." },
  "disco-net": { tr: "Atina'dan disko ağına bağlanın.", en: "Plug into the Athens disco grid." },
  "radio-art-cuban": { tr: "Yunanistan'dan Küba'ya uzanan anten.", en: "An antenna stretched from Greece to Cuba." },
  "skai-100-3": { tr: "Atina'nın gökyüzü frekansı.", en: "Athens' sky frequency." },
  "sveriges-radio-p3": { tr: "İsveç gençliğinin kamusal kanalı.", en: "Sweden's public channel for the young." },
  "vinyl-fm": { tr: "İsveç'ten plak dolabı yayını.", en: "Broadcasting from a Swedish record cabinet." },
  "svt-p1-192kps": { tr: "İsveç'in ağırbaşlı birinci kanalı.", en: "Sweden's stately first channel." },
  "scenesat-radio-mp3": { tr: "Demoscene müziğinin uydusu.", en: "The satellite of demoscene music." },
  "rix-fm-106-7": { tr: "Stokholm'ün hit karışımı.", en: "Stockholm's hit blend." },
  "dansbandskanalen-se": { tr: "İsveç dans orkestraları geçidi.", en: "A parade of Swedish dance bands." },
  "nrk-p3": { tr: "Norveç gençliğinin devlet kanalı.", en: "Norway's public youth channel." },
  "nrk-p1-stor-oslo": { tr: "Oslo'nun gündelik yoldaşı.", en: "Oslo's everyday companion." },
  "p5-nonstop-hits-aac-hq": { tr: "Norveç'ten molasız hit servisi.", en: "Nonstop hit service from Norway." },
  "p12-hitmix-mp3-128k": { tr: "Norveç hit mikserinin çıkışı.", en: "Straight from Norway's hit mixer." },
  "p6-rock-mp3-128k": { tr: "Norveç rock'ının altıncı vitesi.", en: "Norwegian rock in sixth gear." },
  "classic-rock-danmark": { tr: "Danimarka'nın klasik rock ambarı.", en: "Denmark's classic rock barn." },
  "radio-abc": { tr: "Danimarka pop'unun alfabesi.", en: "The ABC of Danish pop." },
  "wmr-world-music-radio": { tr: "Danimarka'dan dünyaya açılan hoparlör.", en: "A Danish loudspeaker aimed at the world." },
  "always-elvis-radio": { tr: "Kral hiç sahneden inmedi.", en: "The King never left the building." },
  "nova-100-dansk": { tr: "Yüzde yüz Danca şarkı sözü.", en: "Lyrics one hundred percent Danish." },
  "doubleclap-radio": { tr: "Helsinki'den çift alkışlı elektronik.", en: "Double-clap electronics from Helsinki." },
  "tick-tock-radio-1950": { tr: "Saat hep 1950'yi gösterir.", en: "The clock is stuck at 1950." },
  "popfm": { tr: "Fin pop'unun gündelik dozu.", en: "The daily dose of Finnish pop." },
  "ylex": { tr: "Finlandiya'nın kamusal genç dalgası.", en: "Finland's public youth wave." },
  "radio-voima": { tr: "Lahti'den yerel güç yayını.", en: "Local power broadcasting from Lahti." },
  "today-fm": { tr: "Dublin'in bugüne ayarlı kanalı.", en: "Dublin's channel tuned to today." },
  "8radio": { tr: "İrlanda'nın bağımsız rock köşesi.", en: "Ireland's independent rock corner." },
  "gem-radio-new-wave": { tr: "Dublin'den yeni dalga mücevherleri.", en: "New wave gems out of Dublin." },
  "easy-radio-ireland-easy-mix": { tr: "İrlanda'da kolay dinleme saati.", en: "Easy listening hours in Ireland." },
  "phever-radio": { tr: "Dublin gecesinin ateşi.", en: "The fever of Dublin nights." },
  "radio-357": { tr: "Dinleyicilerin kurduğu Polonya radyosu.", en: "The Polish station its listeners built." },
  "eska-rock": { tr: "Polonya rock'ının ana caddesi.", en: "The main street of Polish rock." },
  "radio-nowy-wiat-256k": { tr: "Yeni Dünya: bağımsız Polonya yayını.", en: "New World: independent Polish radio." },
  "rock-radio": { tr: "Polonya'dan tavizsiz rock.", en: "Uncompromising rock from Poland." },
  "wnet-fm": { tr: "Varşova'dan söz ve müzik.", en: "Words and music from Warsaw." },
  "vox-fm-128": { tr: "Polonya'nın halk sesi pop'u.", en: "Poland's vox populi pop." },
  "funkstar-radio": { tr: "Çekya'dan funk yıldız tozu.", en: "Funk stardust from Czechia." },
  "radio-beat-128-aac": { tr: "Prag'ın rock nabız ölçeri.", en: "Prague's rock pulse meter." },
  "radio-blanik-morava-a-slezsko": { tr: "Moravya'nın yumuşak pop'u.", en: "Moravia's soft pop." },
  "dance-club-radio": { tr: "Çek dans kulübünün gece vardiyası.", en: "The night shift of a Czech dance club." },
  "kiss-radio-128mp3": { tr: "Prag'a kondurulmuş pop öpücüğü.", en: "A pop kiss planted on Prague." },
  "dance-wave": { tr: "Macaristan'dan kesintisiz dans dalgası.", en: "An unbroken dance wave from Hungary." },
  "oxygen-the-80s-hits": { tr: "Seksenler için saf oksijen.", en: "Pure oxygen for the '80s." },
  "oxygen-magyar-zene": { tr: "Macar şarkılarının nefes borusu.", en: "The windpipe of Hungarian song." },
  "oxygen-classic-rock": { tr: "Klasik rock'a oksijen desteği.", en: "Oxygen support for classic rock." },
  "klubradio-zebradio": { tr: "Budapeşte'nin inatçı bağımsız sesi.", en: "Budapest's stubborn independent voice." },
  "kiss-fm-ro": { tr: "Romanya pop'unun öpücük kanalı.", en: "Romania's pop kiss channel." },
  "one-fm-dance": { tr: "Bükreş pistinin bir numarası.", en: "Number one on the Bucharest floor." },
  "rock-fm-hard-rock": { tr: "Romanya'nın sert rock damarı.", en: "Romania's hard rock vein." },
  "radio-petrecere": { tr: "Rumence eğlencenin düğün salonu.", en: "The wedding hall of Romanian festivity." },
  "super-fm-ro": { tr: "Romanya'dan süper boy pop.", en: "Super-sized pop from Romania." },
  "gensokyo-radio": { tr: "Touhou evreninden fantezi müziği.", en: "Fantasy music from the Touhou universe." },
  "r-a-dio": { tr: "İnternetin anime müzik bodrumu.", en: "The internet's anime-music basement." },
  "free-fm-tokyo": { tr: "Tokyo'dan serbest stil yayın.", en: "Freestyle broadcasting from Tokyo." },
  "box-japan-city-pop": { tr: "Neon ışıklı city pop kutusu.", en: "A neon-lit box of city pop." },
  "big-b-radio-jpop": { tr: "J-pop'un kesintisiz ana damarı.", en: "The uninterrupted mainline of J-pop." },
  "fred-film-radio": { tr: "Sinema sohbetinin Japonca kanalı.", en: "Film talk, Japanese channel." },
  "j-pop-powerplay": { tr: "J-pop'ta güç çalımı.", en: "A power play in J-pop." },
  "listen-moe-j-pop-mp3": { tr: "Anime severlerin ortak kulaklığı.", en: "The shared headphones of anime fans." },
  "big-b-radio-kpop": { tr: "K-pop'un kesintisiz servisi.", en: "K-pop, served without pause." },
  "fred-film-radio-kr": { tr: "Sinema sohbetinin Korece kanalı.", en: "Film talk, Korean channel." },
  "cbs-music-fm": { tr: "Seul'ün ballad yüklü müzik kanalı.", en: "Seoul's ballad-heavy music channel." },
  "mirchi-top-20": { tr: "Bollywood'un acı biberli hit listesi.", en: "Bollywood's chili-hot chart." },
  "mirchi-love": { tr: "Hint aşk şarkılarının baharatı.", en: "The spice of Indian love songs." },
  "rafi-hit-songs": { tr: "Mohammed Rafi'nin ölümsüz sesi.", en: "The immortal voice of Mohammed Rafi." },
  "hindi-gold-radio": { tr: "Hint sinemasının altın plakları.", en: "The golden records of Hindi cinema." },
  "bollywood-2010-s": { tr: "Bollywood'un yakın dönem vitrini.", en: "Bollywood's recent showcase." },
  "kalai-fm-tamil": { tr: "Tamil Nadu'dan sanat frekansı.", en: "An art frequency from Tamil Nadu." },
  "bossa-jazz-brasil": { tr: "Bossa nova ile caz aynı hamakta.", en: "Bossa nova and jazz in one hammock." },
  "smooth-jazz-lounge": { tr: "São Paulo'da yumuşak caz salonu.", en: "A smooth jazz lounge in São Paulo." },
  "radio-mgt-sertanejo": { tr: "Brezilya taşrasının sertanejo sesi.", en: "The sertanejo voice of rural Brazil." },
  "gold-instrumental": { tr: "Sözsüz altın şarkılar rafı.", en: "A shelf of golden instrumentals." },
  "antena-1-porto-alegre": { tr: "Porto Alegre'nin zarif anteni.", en: "Porto Alegre's graceful antenna." },
  "radio-reggae-brasil": { tr: "Brezilya kıyısında reggae salınımı.", en: "Reggae swaying on the Brazilian coast." },
  "mgt-forro": { tr: "Forró: akordeonlu Brezilya dansı.", en: "Forró: Brazil dancing to accordion." },
  "tropical-smooth-jazz": { tr: "Tropik iklimde serin caz.", en: "Cool jazz in a tropical climate." },
  "pobre-johnny": { tr: "Buenos Aires'ten hırpani rock.", en: "Scruffy rock out of Buenos Aires." },
  "fm-la-patriada": { tr: "Arjantin mahallesinin dayanışma radyosu.", en: "The solidarity radio of an Argentine barrio." },
  "radio-shopping": { tr: "Córdoba'dan gündelik rock vitrini.", en: "An everyday rock storefront in Córdoba." },
  "urbana-play-104-4": { tr: "Buenos Aires'in şehirli play tuşu.", en: "Buenos Aires' urban play button." },
  "cafe-romantico-radio-monterrey-online-ww": { tr: "Monterrey'de romantik kahve saati.", en: "Romantic coffee hour in Monterrey." },
  "cumbias-inmortales-radio-monterrey-onlin": { tr: "Ölümsüz cumbia'ların dans pisti.", en: "The dance floor of immortal cumbias." },
  "roca-fm-clasicos-mexico": { tr: "Meksika'nın kaya gibi klasikleri.", en: "Mexico's rock-solid classics." },
  "estrellas-de-los-80s-radio-monterrey-onl": { tr: "Seksenlerin yıldızları Monterrey semasında.", en: "'80s stars over the Monterrey sky." },
  "convoy-en-vivo": { tr: "Mexico City'den canlı rock konvoyu.", en: "A live rock convoy from Mexico City." },
  "reggae-chill-cafe": { tr: "Reggae'nin sakin kafe köşesi.", en: "Reggae's calm café corner." },
  "labgate-progressive-rock": { tr: "Progresif rock laboratuvarı.", en: "A progressive rock laboratory." },
  "100-greatest-of-the-80-s": { tr: "Seksenlerin en büyük yüzü.", en: "The hundred greatest of the '80s." },
  "70-80-90-vibrazioni-rock-radio": { tr: "Üç on yılın rock titreşimi.", en: "Three decades of rock vibration." },
  "nature-radio-rain": { tr: "Müzik yok: yalnızca yağmur.", en: "No music: only rain." },
  "the-prog-rock-machine": { tr: "Progresif rock makinesi; uzun parçalar.", en: "The prog machine; long tracks welcome." },
  "fresh-92-7": { tr: "Adelaide'in taze dans kanalı.", en: "Adelaide's fresh dance channel." },
  "80s-90s-super-pop-hits": { tr: "Avustralya'dan çifte on yıl pop'u.", en: "A double decade of pop from Australia." },
  "free-fm-rock-austral": { tr: "Güney yarımkürenin serbest rock'ı.", en: "Free-range rock from the southern hemisphere." },
  "2me-radio-arabic": { tr: "Avustralya'daki Arapça müzik köprüsü.", en: "An Arabic music bridge in Australia." },
  "2fbi-fbi-radio-94-5-fm-sydney-nsw": { tr: "Sidney'in bağımsız müzik karakolu.", en: "Sydney's independent music outpost." },
  "sbs-popasia": { tr: "Asya pop'unun Avustralya elçiliği.", en: "Asian pop's embassy in Australia." },
  "jakaranda-fm": { tr: "Jakaranda ağaçları altında nostalji.", en: "Nostalgia under the jacaranda trees." },
  "ubuntufm": { tr: "Ubuntu: müzik hepimizin.", en: "Ubuntu: the music belongs to everyone." },
  "amapiano-fm": { tr: "Güney Afrika'nın amapiano nabzı.", en: "South Africa's amapiano pulse." },
  "east-coast-gold": { tr: "Durban kıyısının altın şarkıları.", en: "Golden songs off the Durban coast." },
  "0n-classic-rock": { tr: "Bavyera'dan klasik rock hattı.", en: "A classic rock line from Bavaria." },
  "rmfm-trance": { tr: "Trance'in Alman makine dairesi.", en: "Trance's German engine room." },
  "0nlineradio-soft-rock": { tr: "Yumuşatılmış rock, Alman dozajı.", en: "Rock softened to a German dosage." },
  "huaiji-music": { tr: "Guangdong'dan müzik sesi.", en: "The sound of music from Guangdong." },
  "huayu-500": { tr: "Beş yüz Çince klasiğin arşivi.", en: "An archive of five hundred Chinese classics." },
  "asiafm": { tr: "Kantonca pop'un Asya frekansı.", en: "The Asian frequency of Cantopop." },
  "mixfm-907": { tr: "Çin'den karışık pop sinyali.", en: "A mixed pop signal from China." },
  "radio-vanya": { tr: "Rus pop'unun samimi sofrası.", en: "The warm table of Russian pop." },
  "radio-record-russian-mix": { tr: "Rus dans müziğinin plak şirketi.", en: "The record label of Russian dance." },
  "mixadance-fm": { tr: "Moskova gecesinin dans mikseri.", en: "The dance mixer of Moscow nights." },
  "anon-fm": { tr: "İmzasız yayın: Moskova'nın anonim frekansı.", en: "Unsigned broadcast: Moscow's anonymous frequency." },
  "instrumental-jazz": { tr: "Sözsüz caz; sessizliğe komşu.", en: "Wordless jazz, neighbor to silence." },
  "trance-is-star-radio": { tr: "Ukrayna'dan yıldızlara trance.", en: "Trance to the stars from Ukraine." },
  "brokenbeats": { tr: "Kırık ritimlerin Kiev atölyesi.", en: "Kyiv's workshop of broken beats." },
  "radiorelax-instrumental": { tr: "Kiev'den enstrümantal nefes.", en: "An instrumental breath from Kyiv." },
  "nrj-ukraine": { tr: "Kiev'in yüksek enerji istasyonu.", en: "Kyiv's high-energy station." },
  "radio-90s-eurodance": { tr: "Bozkırda doksanlar eurodance'i.", en: "'90s eurodance on the steppe." },
  "russian-dance-radio": { tr: "Rusça dansın Kazak durağı.", en: "The Kazakh stop of Russian dance." },
  "radio-nostalgie-kazakhstan": { tr: "Kazakistan'ın nostalji rafı.", en: "Kazakhstan's nostalgia shelf." },
  "ns-rock": { tr: "Almatı'dan rock sinyali.", en: "A rock signal from Almaty." },
  "play-radio-serbia": { tr: "Belgrad'ın play tuşu.", en: "Belgrade's play button." },
  "moj-radio": { tr: "'Benim radyom' diyen Sırp kanalı.", en: "The Serbian channel called 'my radio'." },
  "resavski-radio": { tr: "Resava vadisinden yerel yayın.", en: "Local airwaves from the Resava valley." },
  "radio-lola-domaca": { tr: "Sırp şarkılarının ev hali.", en: "Serbian songs, at home." },
  "yammat-fm": { tr: "Zagreb'in şehirli bağımsız radyosu.", en: "Zagreb's urban independent radio." },
  "slavonski-radio": { tr: "Slavonya ovasından rock esintisi.", en: "A rock breeze off the Slavonian plain." },
  "bg-estrada": { tr: "Bulgar estrada'sının sahnesi.", en: "The stage of Bulgarian estrada." },
  "badrock-hard-heavy": { tr: "Bulgaristan'dan sert ve ağır.", en: "Hard and heavy out of Bulgaria." },
  "extreme-deep-house-radio": { tr: "Derin evin uç noktası.", en: "The extreme end of deep house." },
  "seydisfjordur-radio": { tr: "İzlanda fiyordundan topluluk radyosu.", en: "Community radio from an Icelandic fjord." },
  "skyrock-casablanca": { tr: "Kazablanka'nın urban gökyüzü.", en: "Casablanca's urban sky." },
  "aswat-fm": { tr: "Fas'ın sesleri: Aswat.", en: "The voices of Morocco: Aswat." },
  "yabiladi-chaabi-maroc": { tr: "Şaabi: Fas düğünlerinin ritmi.", en: "Chaabi: the rhythm of Moroccan weddings." },
  "amr-diab-radio": { tr: "Yalnızca Amr Diab; Mısır pop'unun yıldızı.", en: "Amr Diab only; Egypt's pop star." },
  "diab-fm": { tr: "Diab hayranlarının ikinci adresi.", en: "The second address for Diab fans." },
  "radio-relax": { tr: "Dubai'de gevşeme kanalı.", en: "A relaxation channel in Dubai." },
  "positively-meditation": { tr: "Meditasyon için olumlu dalga.", en: "A positive wave for meditation." },
  "mettaswara-koplo": { tr: "Cakarta'dan koplo ritmi.", en: "Koplo rhythm from Jakarta." },
  "dengerin-musik-indonesia": { tr: "Endonezya rock'ını dinle.", en: "Listen in on Indonesian rock." },
  "campursari-fm-jakarta": { tr: "Cava müziğinin karışım sanatı.", en: "The blending art of Javanese music." },
  "cool-fahrenheit": { tr: "Bangkok'un serin derecesi.", en: "Bangkok's cool degree." },
  "thai-lanna-radio": { tr: "Kuzey Tayland'ın Lanna ezgileri.", en: "Lanna melodies of northern Thailand." },
  "bkk-fm": { tr: "Bangkok gece elektroniği.", en: "Bangkok night electronics." },
  "bluewave-97": { tr: "Tayland kıyısında mavi dalga.", en: "A blue wave on the Thai coast." },
  "m-radio-vietnam": { tr: "Vietnam pop'unun M kanalı.", en: "Vietnam pop's channel M." },
  "cherry-radio-music-247": { tr: "Vietnam'dan kiraz tadında pop.", en: "Cherry-flavored pop from Vietnam." },
  "star-fm-manila": { tr: "Manila'nın yıldız frekansı.", en: "Manila's star frequency." },
  "win-radio-manila": { tr: "Manila'da kazanan şarkılar.", en: "Winning songs in Manila." },
  "90s-pinoy-alternative": { tr: "Filipin doksanlar alternatifi.", en: "Filipino '90s alternative." },
  "la-retro-80s-chile": { tr: "Şili'nin seksenler retrosu.", en: "Chile's '80s retro." },
  "distorsion-fm": { tr: "Santiago'dan distorsiyonlu yayın.", en: "Distorted broadcasting from Santiago." },
  "radio-contexto-nuble": { tr: "Ñuble bölgesinin bağlam radyosu.", en: "The context radio of Ñuble." },
  "la-mega-medellin": { tr: "Medellín'in mega pop kanalı.", en: "Medellín's mega pop channel." },
  "el-sol-medellin": { tr: "Medellín üzerinde salsa güneşi.", en: "A salsa sun over Medellín." },
  "colombia-salsa-dura": { tr: "Sert salsa: yumuşatılmamış.", en: "Salsa dura: unsoftened." },
  "la-mega-peru": { tr: "Lima'nın mega hit dalgası.", en: "Lima's mega hit wave." },
  "studio-92-lima": { tr: "Lima gençliğinin stüdyosu.", en: "The studio of Lima's youth." },
  "hod-radio": { tr: "Nijerya'dan afrobeats nabzı.", en: "An afrobeats pulse from Nigeria." },
  "kameme-fm": { tr: "Kenya'nın Kikuyu dilli sesi.", en: "Kenya's Kikuyu-language voice." },
  "at254-radio": { tr: "Nairobi'nin +254 kodlu yayını.", en: "Nairobi broadcasting on code +254." },
  "arirang-radio": { tr: "Kore'nin dünyaya açılan K-pop kanalı.", en: "Korea's K-pop channel to the world." },
  "andong-mbc-fm4u": { tr: "Kore ulusal müzik radyosu, Andong aynası.", en: "Korea's national music radio, Andong mirror." },
  "gugak-fm": { tr: "Gugak: Kore'nin geleneksel sarayı.", en: "Gugak: Korea's traditional court." },
  "k-radio-1660": { tr: "New York'taki Kore diasporasının sesi.", en: "The voice of Korean New York." },
};

export function istasyonTanimi(slug: string, dil: string): string | null {
  const t = TANIMLAR[slug];
  if (!t) return null;
  return (dil === "en" && t.en) || t.tr;
}
