// İstasyon kimlikleri — her istasyona bir cümlelik ruh.
// Katalog metnidir; iddia değil atmosfer taşır. Burada olmayan istasyonda satır görünmez.

const TANIMLAR: Record<string, { tr: string; en?: string }> = {
  "arabesk-fm": { tr: "Gece yarısı damar; direksiyon başı arabesk.", en: "Midnight arabesk for the long drive home." },
  "virgin-radio": { tr: "İstanbul'un cilalı pop vitrini.", en: "Istanbul's polished pop storefront." },
  "damar-turk-fm": { tr: "Adı üstünde: damardan, sulandırmadan.", en: "Heartbreak straight from the vein." },
  "kafa-radyo": { tr: "Sabah trafiğinin muhabbetçisi.", en: "Morning-traffic talk and hits." },
  "radyo-7": { tr: "Türkçe popun emektar frekansı.", en: "A veteran of Turkish pop airwaves." },
  "turkulerle-turkiye": { tr: "Memleket hasretine türkü sarar.", en: "Folk songs for homesickness." },
  "radyo-siran": { tr: "Gümüşhane'den yayla havası.", en: "Highland air from Gümüşhane." },
  "metro-fm": { tr: "Şehrin ritmine yabancı hit'ler.", en: "Foreign hits on the city's pulse." },
  "ankara-havalari": { tr: "Başkentin oyun havası; misket ve zeybek.", en: "Ankara's folk-dance frequency." },
  "altin-sarkilar": { tr: "Sararmış fotoğraflardan yükselen şarkılar.", en: "Songs rising from yellowed photographs." },
  "dinamo-sleep": { tr: "Uyumadan önce son frekans.", en: "The last frequency before sleep." },
  "super-fm": { tr: "Doksanlardan beri pop'un ana damarı.", en: "Mainline Turkish pop since the '90s." },
  "90lar": { tr: "Kasetin A yüzü: doksanlar burada bitmedi.", en: "Side A forever: the '90s never ended here." },
  "pal-station": { tr: "Kulüp gecesinin radyodaki hali.", en: "Club night, radio edition." },
  "pal-nostalji": { tr: "Eski aşklar için ışıklar kısık.", en: "Lights dimmed for old flames." },
  "pal-doga": { tr: "Türkü ile dağ havası bir arada.", en: "Folk songs with mountain air." },
  "pop-90": { tr: "Doksanlar pop'u, bitmeyen okul çıkışı.", en: "'90s pop, an endless school run." },
  "dinamo-deep": { tr: "Derin ev; gece yürüyüşlerinin sesi.", en: "Deep house for night walks." },
  "joy-fm": { tr: "Yumuşak pop, sakin ofis saatleri.", en: "Soft pop for calm office hours." },
  "alem-fm": { tr: "Eğlencenin yüksek sesli hali.", en: "The loud end of Turkish pop." },
  "dost-radyo": { tr: "Türkünün dost meclisi.", en: "A friendly gathering of folk songs." },
  "dinamo-caffe": { tr: "Kahve buharına karışan elektronik.", en: "Electronica dissolving into coffee steam." },
  "dinamo-discotheque": { tr: "Aynalı top hâlâ dönüyor.", en: "The mirror ball still spins." },
  "itu-klasik": { tr: "Kampüsten yükselen oda müziği.", en: "Chamber music from campus." },
  "radio-zetzet": { tr: "Cazın geç saat sohbeti.", en: "Jazz's late-night conversation." },
  "turku-radyo": { tr: "Anadolu'nun sözlü hafızası.", en: "Anatolia's sung memory." },
  "sizir-fm": { tr: "Sivas kökünden türkü sızıntısı.", en: "Folk seeping from Sivas roots." },
  "beste-fm": { tr: "Türkçe popun orta şekeri.", en: "Turkish pop, medium sweet." },
  "hey-radyo": { tr: "İzmir'den güler yüzlü pop.", en: "Cheerful pop out of İzmir." },
  "radyo-kent": { tr: "Şehir içi kullanım için pop.", en: "Pop for city use." },
  "ask-fm": { tr: "Adı gibi: bütün şarkılar aşka çıkar.", en: "Every song here leads to love." },
  "joyturk-rock": { tr: "Türkçe rock'ın radyo sahnesi.", en: "The radio stage of Turkish rock." },
  "radyo-odtu-rock": { tr: "Kampüs rock'ı, amfi çıkışı.", en: "Campus rock, straight from the lecture hall." },
  "turk-rock-fm": { tr: "Sazlı gitarlı isyan arşivi.", en: "An archive of Anatolian rebellion." },
  "radyo-a": { tr: "Eskişehir'in kampüs alternatifi.", en: "Eskişehir's campus alternative." },
  "enradio": { tr: "Bağımsız kulaklar için alternatif akış.", en: "An alternative stream for independent ears." },
  "loops-radio": { tr: "Sonsuz döngüde elektronik.", en: "Electronica on infinite loop." },
  "mayday-records": { tr: "Plak çantasından taze elektronik.", en: "Fresh electronica from the record bag." },
  "dinamo-smog": { tr: "Şehir dumanına ayarlı bas.", en: "Bass tuned to city smog." },
  "romantik-ses-isparta": { tr: "Isparta'dan gül kokulu nostalji.", en: "Rose-scented nostalgia from Isparta." },
  "slow-fm": { tr: "Yavaş şarkılar, uzun bakışlar.", en: "Slow songs, long glances." },
  "radyo-arabesk": { tr: "Arabeskin ansiklopedik rafı.", en: "The encyclopedic shelf of arabesk." },
  "radyo-45lik": { tr: "45'lik plakların iğne cızırtısı.", en: "The needle crackle of 45s." },
  "joyturk": { tr: "Türkçe pop'un güncel nabzı.", en: "The current pulse of Turkish pop." },
  "borusan-klasik": { tr: "Konser salonu, cebinde.", en: "A concert hall in your pocket." },
  "park-fm": { tr: "Parkta akşamüstü arabesk.", en: "Arabesk at dusk in the park." },
  "baba-radyo": { tr: "Arabeskin babadan kalma frekansı.", en: "Arabesk, inherited from the elders." },
  "halk-radyo": { tr: "Halkın istek hattı.", en: "The people's request line." },
  "radyo-duet": { tr: "Türkçe pop, çift sesli.", en: "Turkish pop in duet." },
  "can-radyo": { tr: "Candan türküler, cana yakın.", en: "Folk songs, warm and close." },
  "radyo-ekin": { tr: "Türkünün ekin tarlası.", en: "A harvest field of folk song." },
  "radio-antalya": { tr: "Akdeniz akşamına alternatif.", en: "An alternative for Mediterranean evenings." },
  "radyo-gokceada": { tr: "Ada rüzgârıyla gelen pop.", en: "Pop carried on island wind." },
  "slow-turk": { tr: "Türkçe slow'un başkenti.", en: "The capital of Turkish slow." },
  "trt-fm": { tr: "Devlet radyosunun pop kanadı.", en: "The pop wing of public radio." },
  "kral-turk-fm": { tr: "Kral ailesinin Türkçe kanadı.", en: "The Turkish wing of the Kral family." },
  "radyo-seymen": { tr: "Ankara'nın efeleri iş başında.", en: "Ankara's folk bravado on air." },
  "radyo-voyage": { tr: "Sözsüz yolculuk müziği.", en: "Wordless travel music." },
  "gozyasi-fm": { tr: "Adı yeterince açık: mendil hazırla.", en: "The name says it: bring tissues." },
  "kalp-fm": { tr: "Nostaljinin kalp atışı.", en: "Nostalgia's heartbeat." },
  "fakir-fm": { tr: "Arabeskin gururlu yoksulluğu.", en: "The proud poverty of arabesk." },
  "erzincan-cem-radyo": { tr: "Erzincan'dan deyişler ve nefesler.", en: "Alevi hymns and verses from Erzincan." },
  "radyo-odtu": { tr: "ODTÜ'den bağımsız kulak zevki.", en: "Independent taste from METU." },
  "dinamo-fm-locodyno": { tr: "Rayından çıkmış elektronik.", en: "Electronica off the rails." },
  "keyf-station": { tr: "Keyfe keder pop seçkisi.", en: "Pop at leisure." },
  "radyo-eksen": { tr: "Alternatifin İstanbul'daki ekseni.", en: "Istanbul's axis of alternative." },
  "apacik-radyo": { tr: "Açık Radyo: dinleyicisinin omuzlarında.", en: "Listener-funded, fiercely open." },
  "kiyi-caz": { tr: "Kıyıda caz; dalgalar ritim tutar.", en: "Jazz at the shoreline, waves on rhythm." },
  "radyoaura": { tr: "Cazın loş ışıklı salonu.", en: "Jazz in a dim-lit lounge." },
  "radio-mydonose": { tr: "Pistin ışıl ışıl elektroniği.", en: "The dance floor's glittering electronica." },
  "max-fm": { tr: "Rock'ın yüksek voltajlı hattı.", en: "Rock's high-voltage line." },
  "kiss-turk": { tr: "Türkçe pop'a öpücük kondurur.", en: "A kiss blown at Turkish pop." },
  "tgrt-fm": { tr: "Türkçe pop'un aile boyu sofrası.", en: "A family table of Turkish pop." },
  "turkiyem-fm": { tr: "Memleket şarkılarının buluşması.", en: "Where hometown songs meet." },
  "radyo-karadeniz": { tr: "Kemençe rüzgârı, hamsi tadı.", en: "Black Sea wind, kemençe strings." },
  "radyo-alaturka": { tr: "Türk sanat müziğinin fasıl gecesi.", en: "A classical Turkish music soirée." },
  "hayatmix-arabesk": { tr: "Arabeskin karışık kaseti.", en: "The arabesk mixtape." },
  "radyo-turku": { tr: "Türkü burada ev sahibi.", en: "Folk song is the host here." },
  "dt-nostalji": { tr: "Tozlu raflardan seçme nostalji.", en: "Nostalgia picked from dusty shelves." },
  "dijital-slow": { tr: "Yavaşlığın dijital hali.", en: "Slowness, digitized." },
  "retro-turk": { tr: "Retronun Türkçe sözlüsü.", en: "Retro with Turkish lyrics." },
  "radyo-taksi": { tr: "Gece taksisinin radyosu.", en: "The night cab's radio." },
  "ktu": { tr: "Trabzon kampüsünden nostalji.", en: "Nostalgia from the Trabzon campus." },
  "dinamo-fm-legacy": { tr: "dinamo'nun miras arşivi.", en: "dinamo's legacy archive." },
  "dinamo-fm-fluent": { tr: "Akışkan elektronik; kesintisiz.", en: "Fluent, seamless electronica." },
  "loops-radio-progressive": { tr: "Progresif döngünün derin ucu.", en: "The deep end of the progressive loop." },
};

export function istasyonTanimi(slug: string, dil: string): string | null {
  const t = TANIMLAR[slug];
  if (!t) return null;
  return (dil === "en" && t.en) || t.tr;
}
